# Generated by Django 3.2 on 2022-09-22 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aromaticblog', '0003_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='comment_author',
        ),
    ]
